# Generated by Django 5.1 on 2024-10-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='unit_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
