# Generated by Django 5.1 on 2024-10-08 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_phone_number_profile_unit_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=100)),
                ('unit_type', models.CharField(max_length=100)),
                ('issue_description', models.TextField()),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='maintenance_requests/')),
                ('unit_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
